<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Skia" Version="11.2.2" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkiaCharts.Core\SkiaCharts.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Themes\**\*.axaml" />
  </ItemGroup>

</Project>
